### ISSUE TITLE
Port static packages

### ISSUE THREAD

**Issue by senceryazici** [itu-auv/auv-software#3]
Move packages listed below, from [auv-software-legacy](https://github.com/itu-auv/auv-software-legacy) to [auv-software](https://github.com/itu-auv/auv-software)

Port these packages:
- `auv_logger` 
- `auv_cam` 

Create a branch with appropriate branch name, create Pull Request targeting `main`. Attach this issue to the PR you've created. Ask for reviews when you're done, before merging.

**Comment by YunusDiler** [comment]
some directory names in auv-software-legacy are for old name of jetson which is nvidia@jetson, the new name is jetson@ubuntu. they should be changed

**Comment by senceryazici** [comment]
This is already fixed. `auv_logger` is obsolete, and `auv_cam` is already ported. so goodbye.
