### ISSUE TITLE
investigate/fix gazebo realtime factor

### ISSUE THREAD

**Issue by talhabw** [itu-auv/auv-software#87]
gazebo real time factor starts at ~1.00 when the simulation is started. after some time it slows down to the level of ~0.05. possible causes may be:
- unnecessarily big sea world
- something related to our usage of gazebo
- some problem in gazebo 11 unrelated to us

we need to determine the reason and fix it if possible.

**Comment by senceryazici** [comment]
Lets try the pool environment and try to eliminate the first cause

**Comment by senceryazici** [comment]
Also what about the cpu usage? Does it start low and go up when rtf drops? Or is it always high?

**Comment by ozanhakantunca** [comment]
Could you add your findings as comments under the card?  @eminmeydanoglu @optimistprime21 

Did the issue get resolved after transitioning to the pool environment?  
What is the average real-time factor of the data we are receiving?  
As Sencer Yazici mentioned, how is the CPU usage?  
What conclusions have you reached based on your research?  

Adding these outputs to the card would help us make better progress.

**Comment by eminmeydanoglu** [comment]
### Some observations
1. In seabed, rtf is pretty much always low, even at the start.
2. In pool world, rtf is pretty high and stable. 
3. Couldn't observe the rtf going down with time, at least with the pool world. The cpu usage is around 150 (I don't know what the number represents, check ss) and doesn't seem to go up with time. 

![Screenshot from 2024-12-11 19-44-19](https://github.com/user-attachments/assets/a2975cc8-0e9f-4bbc-8214-24dd563e5ce5)
